using Avalonia.Controls; using Avalonia.Platform.Storage; using WorldSeed.DesignSessions; using WorldSeed.LlmIntegration; using WorldSeed.RuleDrafting; using WorldSeed.SourceIngestion;
namespace WorldSeed.App;
public partial class MainWindow : Window {
 readonly HttpClient http=new(); readonly List<DesignSourceNote> notes=[];
 public MainWindow(){InitializeComponent();}
 protected override void OnOpened(EventArgs e){base.OnOpened(e);_=RefreshModelsAsync();}
 async Task RefreshModelsAsync(){try{var m=await new OllamaModelCatalog(http).GetInstalledModelsAsync();ModelSelector.ItemsSource=m.Select(x=>x.Name).ToArray();ModelSelector.SelectedItem=m.Any(x=>x.Name=="gemma3:12b")?"gemma3:12b":m.FirstOrDefault()?.Name;StatusText.Text=m.Count==0?"No local models found.":"Local models refreshed.";}catch{StatusText.Text="Could not reach Ollama. Start it, then refresh.";}}
 async void CheckLocalModels_Click(object? s,Avalonia.Interactivity.RoutedEventArgs e)=>await RefreshModelsAsync();
 void RefreshNotes(){SourceNotesList.ItemsSource=notes.Select(x=>x.Origin!.DisplayName).ToArray();}
 async void AddNotes_Click(object? s,Avalonia.Interactivity.RoutedEventArgs e){var f=await StorageProvider.OpenFilePickerAsync(new FilePickerOpenOptions{AllowMultiple=true,FileTypeFilter=[new FilePickerFileType("Plain text"){Patterns=["*.txt"]}]});var r=f.Select(x=>new PlainTextSourceRequest($"source-{Guid.NewGuid():N}",x.TryGetLocalPath()??"")).Where(x=>x.FilePath.Length>0).ToArray();if(r.Length==0)return;try{notes.AddRange(await new PlainTextSourceImporter().ImportAsync(r));RefreshNotes();StatusText.Text=$"{notes.Count} original note(s) preserved.";}catch(Exception ex){StatusText.Text=ex.Message;}}
 void RemoveSelectedNote_Click(object? s,Avalonia.Interactivity.RoutedEventArgs e){if(SourceNotesList.SelectedIndex is var i&&i>=0&&i<notes.Count){notes.RemoveAt(i);RefreshNotes();StatusText.Text=$"{notes.Count} original note(s) preserved.";}}
 async void CreateSession_Click(object? s,Avalonia.Interactivity.RoutedEventArgs e){if(notes.Count==0||ModelSelector.SelectedItem is not string m){StatusText.Text="Add notes and select a model.";return;}DraftButton.IsEnabled=false;StatusText.Text=$"Drafting with {m}. This can take a few seconds…";DraftText.Text="";var capture=new CapturingClient(new OllamaChatClient(http,OllamaDefaults.CreateProfile("local","Local",m)));try{var svc=new DesignSessionService(new RuleDraftingService(capture));var session=svc.Start($"session-{Guid.NewGuid():N}","local-project","local",notes[0]);foreach(var n in notes.Skip(1))session=svc.AddDesignerMessage(session,n.OriginalText,n);var result=await svc.AdvanceAsync(session);await new JsonDesignSessionStore(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"WorldSeed","sessions")).SaveAsync(result);StatusText.Text="Draft complete and session saved locally.";DraftText.Text=result.LatestTurn!.Action==RuleDraftAction.AskClarifyingQuestion?result.LatestTurn.ClarifyingQuestion:string.Join("\n\n",result.LatestTurn.Draft!.Rules.Select(r=>$"{r.Name}: {r.Text}\nEvidence: {string.Join(" | ",r.SourceSupport.Select(x=>x.Excerpt))}"));}catch(RuleDraftFormatException ex){StatusText.Text="The model returned text WorldSeed could not safely use. Nothing was saved.";DraftText.Text=$"Format detail: {ex.Message}\n\nRaw model output (for diagnosis):\n{Preview(capture.Last?.Content)}";}catch(Exception ex){StatusText.Text="Drafting failed before a usable draft was produced.";DraftText.Text=$"{ex.GetType().Name}: {ex.Message}";}finally{DraftButton.IsEnabled=true;}}
 static string Preview(string? text)=>string.IsNullOrWhiteSpace(text)?"No model response was received.":text.Length>3000?text[..3000]+"\n[truncated]":text;
 protected override void OnClosed(EventArgs e){http.Dispose();base.OnClosed(e);}
 sealed class CapturingClient(ILanguageModelClient inner):ILanguageModelClient{public LlmChatResponse? Last{get;private set;}public async Task<LlmChatResponse> CompleteAsync(LlmChatRequest r,CancellationToken c=default)=>Last=await inner.CompleteAsync(r,c);}
}
